# Generated by Django 4.2.9 on 2024-02-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_measurement_sensor_id_alter_measurement_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
